version: '3'
services:
  node-app:
    container_name: express-node-app-container
    image: computerzman/mhe-docker
    #ports:
    #  - "4000:4000"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - postgres  
      - redis
  postgres:
    container_name: postgres-db-container
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example      
  # mongo:
  #   container_name: mongo-db-container
  #   image: mongo
  #   restart: always
  #   volumes:
  #     - mongo-db:/data/db	
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   container_name: mongo-express-container
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #   depends_on:
  #     - mongo  
  redis:
    container_name: redis-container
    image: redis
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    depends_on:
      - node-app
    ports:
      - "8040:80"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

volumes:
  #mongo-db:
  #  name: my-mongo-db-volume
  postgres-db:
    name: my-postgres-db-volume    