version: '3'
services:
  node-app:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
      - HTTP_PORT=8040
    command: npm run start-dev
